VIEWING EVENT ORGANISER TABLE, USING SELECT STATEMENT
SELECT * FROM Event_Organiser;

VIEWING PARTICIPANT TABLE ,USING SELECT STATEMENT
SELECT * FROM Participant;
VEIWING EVENT TABLE ,USING SELECT STATEMENT
SELECT * FROM Event;
VIEWING CATEGORY TABLE ,USING SELECT STATEMENTE
SELECT * FROM Category;
VIEWING REGISTRATION TABLE, USING SELECT STATEMENT
SELECT * FROM Registration;
VIEWING  RESULT Table, USING SELECT STATEMENT
SELECT * FROM Result;
VIEWING ROUTE TABLE, USING SELECT STATEMENT 
SELECT * FROM Route;
VIEWING WEATHER INFORMATION TABLE, USING SELECT STATEMENT
SELECT * FROM WeatherInformation;
